export const GET_BOOK_LIST_ERROR = 'GET_BOOK_LIST_ERROR';
export const GET_BOOK_LIST_REQUEST = 'GET_BOOK_LIST_REQUEST';
export const GET_BOOK_LIST_SUCCESS = 'GET_BOOK_LIST_SUCCESS';
export const SET_TOKEN = 'SET_TOKEN';
